c.ExtensionApp.open_browser = False
c.ServerApp.allow_remote_access = True
c.ServerApp.allow_root = True
c.ServerApp.token = ''
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.port = 8888
c.ServerApp.terminado_settings = {'shell_command': ['/bin/zsh']}
c.ServerApp.answer_yes = True
c.ContentsManager.allow_hidden = True
c.ContentsManager.root_dir = '/'
c.LabApp.user_settings_dir = '/work/jupyter/user-settings'
c.LabApp.workspaces_dir = '/work/jupyter/workspaces'
